config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events
  resources :folders
  get '/events/:id/save', to: 'events#save', as: 'event_save'
  post '/events/:id/select', to: 'events#select', as: 'event_select'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :events
  validates :name, presence: true
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  def show
    @folder = Folder.find(params[:id])
    @events = @folder.events
    @event = Event.new
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Evenements_CustomerSurvey.xlsx"'
      }
    end
  end

  def new
    @folder = Folder.new
    @events = Event.where(user_id: current_user.id).where(folder_id: nil).order(date: :desc)
  end

  def create
    @folder = Folder.new(folder_params)
    @folder.user_id = current_user.id
    if @folder.save
      params[:folder][:events].delete_if(&:empty?)
      unless params[:folder][:events].empty?
        params[:folder][:events].each do |event_id|
          event = Event.find(event_id.to_i)
          event.folder_id = @folder.id
          event.save
        end
      end
      redirect_to events_path, notice: "Nouveau dossier créé"
    else
      redirect_to events_path, alert: "Le nouveau dossier n'a pu être créé"
    end
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def update
    respond_to do |format|
      format.html {
        @folder = Folder.find(params[:id])
        @folder.update(folder_params)
        redirect_to folder_path(@folder.id), notice: "Le dossier a été édité"
      }
      format.json {
        @folder = Folder.find(params["id"])
        @event = Event.find(params["folder"]["id"])
        @event.folder_id = @folder.id
        @event.save
      }
    end

  end

  def destroy
    @folder = Folder.find(params[:id])
    @events = Event.where(folder_id: @folder.id)
    if params[:all] == "true"
      @events.destroy_all
      @folder.destroy
      redirect_to events_path, notice: "Le dossier et ses évènements ont été supprimé"
    else
      @events.each do |event|
        event.folder_id = nil
        event.save
      end
      @folder.destroy
      redirect_to events_path, notice: "Le dossier a été supprimé"
    end
  end


  private

  def folder_params
    params.require(:folder).permit(:name)
  end
end

app/views/folders/edit.html.erb
<div class="container">
  <div class="back-link">
    <%= link_to :back do %>
      <i class="fa fa-arrow-left"></i>
    <% end %>
  </div>
  <h2 class="text-center events-title">Editer le dossier</h2>
  <%= simple_form_for(@folder) do |f| %>
    <div id="new-event-form" class="form-inputs">
      <%= f.input :name,
                  label: 'Nom',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" } %>
    </div>
    <div class="form-actions">
      <%= link_to "Annuler", folder_path(@folder.id), class:'btn btn-danger' %>
      <%= f.button :submit, "Enregistrer", class:'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/folders/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="back-link">
    <%= link_to events_path do %>
      <i class="fa fa-arrow-left"></i>
    <% end %>
  </div>
  <h2 class="text-center events-title">Créer un nouveau dossier</h2>
  <%= simple_form_for(@folder) do |f| %>
    <div id="new-folder-form" class="form-inputs">
      <%= f.input :name,
                  label: 'Nom',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" } %>
      <%= f.input :events, collection: @events, :label_method => :event_label, :value_method => :id,:label => "Evènements" ,:include_blank => false, input_html: { multiple: true } %>
    </div>
    <div class="form-actions new__folder__actions">
      <%= link_to "Annuler", events_path, class:'btn btn-danger' %>
      <%= f.button :submit, "Enregistrer", class:'btn btn-primary', id:"save-new-event" %>
    </div>
  <% end %>
</div>

app/views/folders/show.html.erb
<div class="container events-container">
  <div class="back-link">
    <%= link_to events_path do %>
      <i class="fa fa-arrow-left"></i>
    <% end %>
  </div>

  <h2 class="events__title"><%= image_tag 'folder.png', width:"35px", height:"25px" %> <%= @folder.name.capitalize %></h2>
  <div class="download-link-container">
    <div class="folder__edit__links">
      <%= link_to edit_folder_path(@folder.id) do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <i class="fa fa-trash folder-delete-button" aria-hidden="true" id='<%= @folder.id %>'></i>
      <%= link_to "delete", folder_path(@folder.id, all: false), class:'hidden', id:"folder-delete-link-#{@folder.id}", method: 'delete' %>
      <%= link_to "delete", folder_path(@folder.id, all: true), class:'hidden', id:"folder-delete-link-#{@folder.id}-all", method: 'delete' %>
    </div>
    <% unless @events.count.zero? %>
      <%= link_to folder_path(id: @folder.id, format: :xlsx) do %>
        <%= fa_icon "file-excel-o" %>
      <% end %>
    <% end %>
  </div>

  <% if @events.count.zero? %>
    <h6 class="text-center mt-4 mb-4">Aucun évenement créé</h6>
  <% else %>
    <% @events.each do |event| %>
      <%= render "events/index_card", event:event %>
    <% end %>
  <% end %>
  <div class="new-event-button-container">
    <div class="btn btn-success mt-4", id="new-event-button">
      Créer un nouvel évènement
    </div>
    <%# <div class="arrow-down hide-arrow"> %>
      <%#= fa_icon "arrow-down" %>
    <%# </div> %>
  </div>
  <div class="index-new-modal">
    <div id="new-modal" class="hidden mt-4">
      <%= render "events/new", folder:@folder %>
    </div>
  </div>
</div>