config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events
  resources :folders
  get '/events/:id/save', to: 'events#save', as: 'event_save'
  post '/events/:id/select', to: 'events#select', as: 'event_select'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, :location, presence: true
  belongs_to :user, dependent: :destroy
  belongs_to :folder, optional: true
  def event_label
    "#{self.date.strftime('%d/%m/%Y')} - #{self.name.capitalize}"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @folders = Folder.where(user_id: current_user.id)
    @all_events = Event.where(user_id: current_user.id)
    @events = Event.where(user_id: current_user.id).where(folder_id: nil).order(date: :desc)
    @event = Event.new
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Evenements_CustomerSurvey.xlsx"'
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.pdf do
        generate_pdf(@event)
      end
    end
  end

  def new
    @event = Event.new
    @folders = Folder.where(user_id: current_user.id)
  end

  def create
    @event = Event.new(event_params)
    if params[:event][:folder].present?
      @event.folder_id = params[:event][:folder]
    end
    @event.user_id = current_user.id
    @event.good = 0
    @event.bad = 0
    @event.middle = 0
    @event.total = 0
    all_events_unselected
    @event.selected = true
    respond_to do |format|
      if @event.save
        if params[:event][:folder].present?
          format.html { redirect_to folder_path(params[:event][:folder]), notice: "Votre nouvel évènement a été créé" }
        else
          format.html { redirect_to request.referrer, notice: "Votre nouvel évènement a été créé" }
        end
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { redirect_to request.referrer, alert: "Une erreur s'est produite, la nouvel évènement n'a pu être créé" }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @folders = Folder.where(user_id: current_user.id)
  end

  def update
    @event = Event.find(params[:id])
    if params[:remove_folder].present?
      @folder = @event.folder
      @event.folder_id = nil
      if @event.save
        redirect_to folder_path(@folder.id), notice: "L'évènement a été retiré du dossier"
      end
    else
    @event.update(event_params)
      if params[:event][:folder].present?
        @folder = Folder.find(params[:event][:folder])
        @event.folder_id = @folder.id
        if @event.save
          redirect_to folder_path(@folder.id), notice: "L'évènement a été édité"
        else
          render :edit
        end
      elsif params[:event][:folder].empty? && @event.folder.present?
        @event.folder_id = nil
        if @event.save
          redirect_to events_path, notice: "L'évènement a été édité"
        else
          render :edit
        end
      else
        if @event.save
          if @event.folder
            redirect_to folder_path(@event.folder.id), notice: "L'évènement a été édité"
          else
            redirect_to events_path, notice: "L'évènement a été édité"
          end
        else
          render :edit
        end
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to request.referrer, notice: "L'évènement a été supprimé"
  end

  def save
    @event = Event.find(params[:id])
    if params[:replace] == 'true'
      @event.good = params[:good].to_i
      @event.middle = params[:middle].to_i
      @event.bad = params[:bad].to_i
      @event.total = params[:bad].to_i + params[:good].to_i + params[:middle].to_i
    else
      good = @event.good + params[:good].to_i
      bad = @event.bad + params[:bad].to_i
      middle = @event.middle + params[:middle].to_i
      @event.good = good
      @event.bad = bad
      @event.middle = middle
      @event.total = (good.to_i + bad.to_i + middle.to_i)
    end
    @event.save
  end

  def select
    @event = Event.find(params[:id])
    if @event.selected
      @event.selected = false
    else
      all_events_unselected
      @event.selected = true
    end
    @event.save
    redirect_to request.referrer
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :tag_line, :date, :folder_id)
  end

  def all_events_unselected
    Event.all.each do |event|
      event.selected = false
      event.save
    end
  end

  def generate_pdf(event)
    unless event.good.zero?
      good_pc = ((event.good * 100) / event.total) * 2
      middle_pc = ((event.middle * 100) / event.total) * 2
      bad_pc = ((event.bad * 100) / event.total) * 2
      total = 200
      satisfaction = ((((@event.middle.to_f / 2) + (@event.good))*100).to_f / @event.total).round(2)
    end

    pdf = Prawn::Document.new
    # pdf.fill_color('0000ff')

    pdf.image "#{Rails.root}/app/assets/images/Customer.png", :at => [0,730], :width => 80, :height => 80
    pdf.text "Customer Satisfaction", size: 32, align: :center
    pdf.text "Survey", size: 32, align: :center
    pdf.text " "
    pdf.text " "
    pdf.text " "
    pdf.text " "
    pdf.text event.name, size: 22
    pdf.text event.date.strftime('%d/%m/%Y'), size: 16
    pdf.text event.location, size: 16
    pdf.text " "
    pdf.text " "
    pdf.text " "
    pdf.text "Résultats :", size: 16
    pdf.text " "

    unless event.total.zero?
      x = 150
      y = 200
      bad_x = x
      middle_x = x+100
      good_x = x+200
      total_x = x+300
      pdf.blend_mode(:Multiply) do
        pdf.fill_color('ff6b6b')
        pdf.fill_rectangle([bad_x, bad_pc+y], 50, bad_pc)
        pdf.stroke_color 0, 255, 0, 0
        pdf.stroke_rectangle [bad_x, bad_pc+y], 50, bad_pc
      end
      pdf.blend_mode(:Multiply) do
        pdf.fill_color('f9f61d')
        pdf.fill_rectangle([middle_x, middle_pc+y], 50, middle_pc)
        pdf.stroke_color 'f2eb1f'
        pdf.stroke_rectangle [middle_x, middle_pc+y], 50, middle_pc
      end
      pdf.blend_mode(:Multiply) do
        pdf.fill_color('0ecb43')
        pdf.fill_rectangle([good_x, good_pc+y], 50, good_pc)
        pdf.stroke_color 255, 0, 0, 0
        pdf.stroke_rectangle [good_x, good_pc+y], 50, good_pc
      end
        pdf.blend_mode(:Multiply) do
        pdf.fill_rectangle([total_x, total+y], 50, total)
      end

      pdf.stroke_color '000000'

      pdf.stroke_axis(
        at: [50, 200], width: 420, height: 220,
        step_length: 500, negative_axes_length: 10, color: '000000')


      pdf.dash([1, 2, 3, 2, 1, 5], phase: 6)
      pdf.stroke_horizontal_line 50, bad_x, at: bad_pc+y
      pdf.dash([1, 2, 3, 2, 1, 5], phase: 6)
      pdf.stroke_horizontal_line 50, middle_x, at: middle_pc+y
      pdf.dash([1, 2, 3, 2, 1, 5], phase: 6)
      pdf.stroke_horizontal_line 50, good_x, at: good_pc+y
      pdf.dash([1, 2, 3, 2, 1, 5], phase: 6)
      pdf.stroke_horizontal_line 50, total_x, at: total+y

      pdf.draw_text "Mauvais (#{event.bad})", :at => [bad_x-5 , y-20 ]
      pdf.draw_text "Moyen (#{event.middle})", :at => [middle_x , y-20 ]
      pdf.draw_text "Bon (#{event.good})", :at => [good_x+5 , y-20 ]
      pdf.draw_text "Total (#{event.total})", :at => [total_x+5 , y-20 ]

      pdf.draw_text "#{bad_pc/2}%", :at => [15 , bad_pc+y-5 ]
      pdf.draw_text "#{middle_pc/2}%", :at => [15 , middle_pc+y-5 ]
      pdf.draw_text "#{good_pc/2}%", :at => [15 , good_pc+y-5 ]
      pdf.draw_text "#{total/2}%", :at => [15 , total+y-5 ]

      pdf.draw_text "Taux de satisfaction: #{satisfaction} %", size: 18, :at => [140, 80]

    else
      pdf.text "Pas de donné pour cet évènement"
    end
    send_data pdf.render,
      filename: "CustomerSurvey #{event.date.strftime('%d/%m/%Y')}.pdf",
      type: 'application/pdf',
      disposition: 'inline'
  end
end

app/views/events/_folder_card.html.erb
<%= link_to folder_path(folder.id), class:"droppable" do %>
  <div class="folders__item">
    <% if folder.events.pluck(:selected).include?(true) %>
      <div class="selected folder__mark"><%= fa_icon "check" %></div>
    <% end %>
    <%= image_tag 'folder.png', width:"140px", height:"100px" %>
    <div class="folder__susbitlte">
      <h6><%= folder.name.capitalize %></h6>
    </div>
  </div>
<% end %>

app/views/events/_index_card.html.erb
<div class="stats-item" id="stats-item-<%= event.id %>" data-id="<%= event.id %>">
  <div class="stat-header">
    <div class="stat-header-left">
      <h5 class=<%= controller_name == 'events' ? 'stat-item-drag-target' : '' %> data-id="<%= event.id %>"><%= event.date.strftime('%d/%m/%Y') %> - <%= event.name.capitalize %></h5>
      <%= link_to event_select_path(event.id), method: :post, class:"#{event.selected ? "selected" : "unselected"}" do %>
        <%= fa_icon "check" %>
      <% end %>
    </div>

    <div class="stat-header-right">
      <%= link_to event_path(id: event.id, format: :pdf) do %>
        <%= fa_icon "file-pdf-o" %>
      <% end %>

      <% if controller_name == "folders" && action_name == "show" %>
      <div class="remove__from__folder">
        <%= link_to event_path(id: event.id, remove_folder: 'true'), method: :patch do %>
          <%= fa_icon "folder" %>
          <span>-</span>
        <% end %>
      </div>
      <% end %>

      <%= link_to edit_event_path(event.id, from: controller_name) do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <i class="fa fa-trash event-delete-button" aria-hidden="true" id='<%= event.id %>'></i>
      <%= link_to "delete", event_path(event.id), class:'hidden', id:"event-delete-link-#{event.id}", method: 'delete' %>
    </div>
  </div>
  <h7><%= event.location %></h7>
  <% if event.total && !event.total.zero? %>

    <div class="event__chart__container" id="container-<%= event.id %>">
      <div class="event__chart__content hide-content" id="content-<%= event.id %>">

    <canvas id="myChart" width="400" max-height="200" data-good="<%= event.good %>" data-middle="<%= event.middle %>" data-bad="<%= event.bad %>" data-total="<%= event.total %>"></canvas>

    <div class="chart-labels chart-label-pourcent">
      <div class="chart-labels-item">
        <h7><%= ((event.bad * 100) / event.total).ceil %>%</h7>
      </div>
      <div class="chart-labels-item">
        <h7><%= ((event.middle * 100) / event.total).ceil %>%</h7>
      </div>
      <div class="chart-labels-item">
        <h7><%= ((event.good * 100) / event.total).ceil %>%</h7>
      </div>
      <div class="chart-labels-item">
        <h7>100%</h7>
      </div>
    </div>

    <div class="chart-labels">
            <div class="chart-labels-item">
              <div class="th-smiley">
                <%= image_tag 'dislike.png', height: '25', width: '25'  %>
              </div>
            </div>
          <div class="chart-labels-item">
            <div class="th-smiley">
              <%= image_tag 'middle.png', height: '25', width: '25'  %>
            </div>
          </div>
          <div class="chart-labels-item">
            <div class="th-smiley">
              <%= image_tag 'like.png', height: '25', width: '25'  %>
            </div>
          </div>
          <div class="chart-labels-item">
            Total
          </div>
        </div>
      </div>
    </div>

  <div class="unfold__arrow__container" id="<%= event.id %>">
    <%= fa_icon 'angle-down', id: event.id %>
  </div>
    <%#= render 'stats_table', event:event %>
  <% else %>
    <h6 class='mt-4 text-center'>Aucune donnée pour cet évènement</h6>
  <% end %>
</div>

app/views/events/_new.html.erb
<%= simple_form_for(@event, as: :event, method: :post, url: events_path) do |f| %>
  <div id="new-event-form" class="form-inputs">
    <%= f.input :name,
                label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" } %>
    <%= f.input :location,
                label: 'Lieu',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "location" } %>
    <%= f.input :date, as: :date, start_year: Date.today.year,
                end_year: Date.today.year - 2,
                order: [:day, :month, :year],
                label: 'Date',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "date" } %>
    <%= f.input :tag_line,
                label: 'Titre',
                placeholder: 'ex: Avez vous apprécier notre présentation?',
                required: false,
                autofocus: true,
                hint: "Titre affiché au dessus du vote (par défault: 'Donnez nous votre avis!')",
                input_html: { autocomplete: "tag_line" } %>
    <% if controller_name == 'folders' && action_name == 'show' %>
      <%= f.input :folder, :as => :hidden, :input_html => { :value => folder.id } %>
    <% else %>
      <% if @folders && !@folders.count.zero? %>
        <%= f.input :folder, :collection => @folders, :value_method => :id, :label => "Dossier" ,:include_blank => true %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Annuler", class:'btn btn-danger', id:"cancel-new-event" %>
    <%= f.button :submit, "Enregistrer", class:'btn btn-primary', id:"save-new-event" %>
  </div>
<% end %>

app/views/events/_new_modal.html.erb
<%= simple_form_for(@event, as: :event, method: :post, url: events_path) do |f| %>
  <div id="new-event-form" class="form-inputs">
    <%= f.input :name,
                label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" } %>
    <%= f.input :location,
                label: 'Lieu',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "location" } %>
    <%= f.input :date, as: :date, start_year: Date.today.year,
                end_year: Date.today.year - 2,
                order: [:day, :month, :year],
                label: 'Date',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "date" } %>
    <%= f.input :tag_line,
                label: 'Titre',
                placeholder: 'ex: Avez vous apprécier notre présentation?',
                required: false,
                autofocus: true,
                hint: "Titre affiché au dessus du vote",
                input_html: { autocomplete: "tag_line" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Annuler", class:'btn btn-danger' %>
    <%= f.button :submit, "Enregistrer", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/events/_stats_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'dislike.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'middle.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'like.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">N</th>
      <td><%= event.bad %></td>
      <td><%= event.middle %></td>
      <td><%= event.good %></td>
      <td><%= event.total %></td>
    </tr>
    <tr>
      <th scope="row">%</th>
      <% if event.total == 0 %>
        <td>0%</td>
        <td>0%</td>
        <td>0%</td>
      <% else %>
        <td><%= ((event.bad * 100) / event.total).round %>%</td>
        <td><%= ((event.middle * 100) / event.total).round %>%</td>
        <td><%= ((event.good * 100) / event.total).round %>%</td>
      <% end %>
      <td>100%</td>
    </tr>
  </tbody>
</table>

app/views/events/edit.html.erb
<div class="container edit-container" data-folder= <%= @event.folder ? @event.folder.id : nil %> >
  <%= simple_form_for(@event, as: :event, method: :patch, url: event_path) do |f| %>
    <div id="new-event-form" class="form-inputs">
      <%= f.input :name,
                  label: 'Nom',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" } %>
      <%= f.input :location,
                  label: 'Lieu',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "location" } %>
      <%= f.input :date, as: :date, start_year: Date.today.year,
                  end_year: Date.today.year - 2,
                  order: [:day, :month, :year],
                  label: 'Date',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "date" } %>
      <%= f.input :tag_line,
                  label: 'Titre',
                  placeholder: 'ex: Avez vous apprécier notre présentation?',
                  hint: "Titre affiché au dessus du vote (par défault: 'Donnez nous votre avis!')",
                  required: false,
                  autofocus: true,
                  input_html: { autocomplete: "tag_line" } %>
      <%= f.input :folder, :collection => @folders, :label => "Dossier", value_method: :id, :include_blank => true, input_html: { autocomplete: "folder" } %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Enregistrer", class:'btn btn-primary', id:"save-new-event" %>
      <%= f.button :submit, "Annuler", class:'btn btn-danger', id:"cancel-new-event" %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container events-container">
  <%= render 'shared/back_link' %>
  <h2 class="text-center events-title">Evènements</h2>

  <% unless @folders.count.zero? %>
    <div class="folders__container">
      <% @folders.each do |folder| %>
        <%= render 'folder_card', folder:folder %>
      <% end %>
    </div>
  <% end %>

  <div class="download-link-container">
    <%= link_to new_folder_path do %>
    <div class="new__folder__icon">
      <%= fa_icon "folder" %>
      <span>+</span>
    </div>
    <% end %>
    <% unless @events.count.zero? %>
      <%= link_to events_path(format: :xlsx) do %>
        <%= fa_icon "file-excel-o" %>
      <% end %>
    <% end %>
  </div>

  <% if @all_events.count.zero? %>
    <h6 class="text-center mt-4 mb-4">Aucun évenement créé</h6>
  <% else %>
  <div class="index__cards_container">
    <% @events.each do |event| %>
      <%= render "index_card", event:event %>
    <% end %>
  <% end %>
  </div>
  <div class="new-event-button-container">
    <div class="btn btn-success mt-4", id="new-event-button">
      Créer un nouvel évènement
    </div>
    <%# <div class="arrow-down hide-arrow"> %>
      <%#= fa_icon "arrow-down" %>
    <%# </div> %>
  </div>
  <div class="index-new-modal">
    <div id="new-modal" class="hidden mt-4">
      <%= render "events/new" %>
    </div>
  </div>
</div>