config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :events
  resources :folders
  get '/events/:id/save', to: 'events#save', as: 'event_save'
  post '/events/:id/select', to: 'events#select', as: 'event_select'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/day.rb
class Day < ApplicationRecord
  validates :name, :date, :location, presence: true
  belongs_to :user
  belongs_to :folder, optional: true

  def day_label
    "#{self.date.strftime('%d/%m/%Y')} - #{self.name.capitalize}"
  end
end

app/views/days/_family_card.html.erb
<%= link_to family_path(family.id) do %>
  <div class="folders__item">
    <%= image_tag 'folder.png', width:"140px", height:"100px" %>
    <h6><%= family.name.capitalize %></h6>
  </div>
<% end %>

app/views/days/_folder_card.html.erb
<%= link_to folder_path(folder.id) do %>
  <div class="folders__item">
    <% if folder.days.pluck(:selected).include?(true) %>
      <div class="selected folder__mark"><%= fa_icon "check" %></div>
    <% end %>
    <%= image_tag 'folder.png', width:"140px", height:"100px" %>
    <div class="folder__susbitlte">
      <h6><%= folder.name.capitalize %></h6>
    </div>
  </div>
<% end %>

<%# folder.days.pluck(:selected).include?(true) %>

app/views/days/_index_card.html.erb
<div class="stats-item">
  <div class="stat-header">
    <div class="stat-header-left">
      <h5><strong><%= day.date.strftime('%d/%m/%Y') %> - <%= day.name.capitalize %></strong></h5>
      <%= link_to day_select_path(day.id), method: :post, class:"#{day.selected ? "selected" : "unselected"}" do %>
        <%= fa_icon "check" %>
      <% end %>
    </div>
    <div class="stat-header-right">
      <%= link_to day_path(id: day.id, format: :pdf) do %>
        <%= fa_icon "file-pdf-o" %>
      <% end %>
      <%= link_to edit_day_path(day.id) do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <i class="fa fa-trash day-delete-button" aria-hidden="true" id='<%= day.id %>'></i>
      <%= link_to "delete", day_path(day.id), class:'hidden', id:"day-delete-link-#{day.id}", method: 'delete' %>
    </div>
  </div>
  <h7><%= day.location %></h7>
  <% if day.total && !day.total.zero? %>
    <canvas id="myChart" width="400" max-height="200" data-good="<%= day.good %>" data-middle="<%= day.middle %>" data-bad="<%= day.bad %>" data-total="<%= day.total %>"></canvas>

    <div class="chart-labels">
            <div class="chart-labels-item">
              <div class="th-smiley">
                <%= image_tag 'dislike.png', height: '25', width: '25'  %>
              </div>
            </div>
            <div class="chart-labels-item">
              <div class="th-smiley">
                <%= image_tag 'middle.png', height: '25', width: '25'  %>
              </div>
            </div>
            <div class="chart-labels-item">
              <div class="th-smiley">
                <%= image_tag 'like.png', height: '25', width: '25'  %>
              </div>
            </div>
          <div class="chart-labels-item">
            Total
          </div>
    </div>

    <%#= render 'stats_table', day:day %>
  <% else %>
    <h6 class='mt-4 text-center'>Aucune donnée pour cet évènement</h6>
  <% end %>
</div>

app/views/days/_new.html.erb
<%= simple_form_for(@day, as: :day, method: :post, url: days_path) do |f| %>
  <div id="new-day-form" class="form-inputs">
    <%= f.input :name,
                label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" } %>
    <%= f.input :location,
                label: 'Lieu',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "location" } %>
    <%= f.input :date, as: :date, start_year: Date.today.year,
                end_year: Date.today.year - 2,
                order: [:day, :month, :year],
                label: 'Date',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "date" } %>
    <%= f.input :tag_line,
                label: 'Titre',
                placeholder: 'ex: Avez vous apprécier notre présentation?',
                required: false,
                autofocus: true,
                hint: "Titre affiché au dessus du vote (par défault: 'Donnez nous votre avis!')",
                input_html: { autocomplete: "tag_line" } %>
    <% if controller_name == 'folders' && action_name == 'show' %>
      <%= f.input :folder, :as => :hidden, :input_html => { :value => folder.id } %>
    <% else %>
      <% if @folders && !@folders.count.zero? %>
        <%= f.input :folder, :collection => @folders, :value_method => :id, :label => "Dossier" ,:include_blank => true %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Annuler", class:'btn btn-danger', id:"cancel-new-day" %>
    <%= f.button :submit, "Enregistrer", class:'btn btn-primary', id:"save-new-day" %>
  </div>
<% end %>

app/views/days/_new_modal.html.erb
<%= simple_form_for(@day, as: :day, method: :post, url: days_path) do |f| %>
  <div id="new-day-form" class="form-inputs">
    <%= f.input :name,
                label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" } %>
    <%= f.input :location,
                label: 'Lieu',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "location" } %>
    <%= f.input :date, as: :date, start_year: Date.today.year,
                end_year: Date.today.year - 2,
                order: [:day, :month, :year],
                label: 'Date',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "date" } %>
    <%= f.input :tag_line,
                label: 'Titre',
                placeholder: 'ex: Avez vous apprécier notre présentation?',
                required: false,
                autofocus: true,
                hint: "Titre affiché au dessus du vote",
                input_html: { autocomplete: "tag_line" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Annuler", class:'btn btn-danger' %>
    <%= f.button :submit, "Enregistrer", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/days/_stats_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'dislike.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'middle.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>
        <div class="th-smiley">
          <%= image_tag 'like.png', height: '25', width: '25'  %>
        </div>
      </th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">N</th>
      <td><%= day.bad %></td>
      <td><%= day.middle %></td>
      <td><%= day.good %></td>
      <td><%= day.total %></td>
    </tr>
    <tr>
      <th scope="row">%</th>
      <% if day.total == 0 %>
        <td>0%</td>
        <td>0%</td>
        <td>0%</td>
      <% else %>
        <td><%= ((day.bad * 100) / day.total).round %>%</td>
        <td><%= ((day.middle * 100) / day.total).round %>%</td>
        <td><%= ((day.good * 100) / day.total).round %>%</td>
      <% end %>
      <td>100%</td>
    </tr>
  </tbody>
</table>

app/views/days/edit.html.erb
<div class="container">
  <%= simple_form_for(@day, as: :day, method: :patch, url: day_path) do |f| %>
    <div id="new-day-form" class="form-inputs">
      <%= f.input :name,
                  label: 'Nom',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" } %>
      <%= f.input :location,
                  label: 'Lieu',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "location" } %>
      <%= f.input :date, as: :date, start_year: Date.today.year,
                  end_year: Date.today.year - 2,
                  order: [:day, :month, :year],
                  label: 'Date',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "date" } %>
      <%= f.input :tag_line,
                  label: 'Titre',
                  placeholder: 'ex: Avez vous apprécier notre présentation?',
                  hint: "Titre affiché au dessus du vote (par défault: 'Donnez nous votre avis!')",
                  required: false,
                  autofocus: true,
                  input_html: { autocomplete: "tag_line" } %>
      <%= f.input :folder, :collection => @folders, value:@day.folder , :value_method => :id, :label => "Dossier" ,:include_blank => true %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Enregistrer", class:'btn btn-primary', id:"save-new-day" %>
      <%= f.button :submit, "Annuler", class:'btn btn-danger', id:"cancel-new-day" %>
    </div>
  <% end %>
</div>

app/views/days/index.html.erb
<div class="container days-container">
  <%= render 'shared/back_link' %>
  <h2 class="text-center days-title">Evènements</h2>

  <% unless @folders.count.zero? %>
    <div class="folders__container">
      <% @folders.each do |folder| %>
        <%= render 'folder_card', folder:folder %>
      <% end %>
    </div>
  <% end %>

  <div class="download-link-container">
    <%= link_to new_folder_path do %>
    <%= fa_icon "folder" %>
    <% end %>
    <% unless @days.count.zero? %>
      <%= link_to days_path(format: :xlsx) do %>
        <%= fa_icon "file-excel-o" %>
      <% end %>
    <% end %>
  </div>

  <% if @all_days.count.zero? %>
    <h6 class="text-center mt-4 mb-4">Aucun évenement créé</h6>
  <% else %>
    <% @days.each do |day| %>
      <%= render "index_card", day:day %>
    <% end %>
  <% end %>
  <div class="new-day-button-container">
    <div class="btn btn-success mt-4", id="new-day-button">
      Créer un nouvel évènement
    </div>
    <%# <div class="arrow-down hide-arrow"> %>
      <%#= fa_icon "arrow-down" %>
    <%# </div> %>
  </div>
  <div class="index-new-modal">
    <div id="new-modal" class="hidden mt-4">
      <%= render "days/new" %>
    </div>
  </div>
</div>